name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ap-southeast-1
  REMOTE_HOST: ec2-18-143-170-77.ap-southeast-1.compute.amazonaws.com
  REMOTE_USER: ec2-user

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure SSH
        env:
          SSH_HOST: ${{ env.REMOTE_HOST }}
          SSH_USER: ${{ env.REMOTE_USER }}
          SSH_KEY: ${{ secrets.SSH_EC2_KEY }} 
      - name: List home directory
        run: ssh ec2 'ls -la'
      - name: build project
        run: docker build . --file Dockerfile --tag shopee-food-clone-ui:$(date +%s)
      - name: run project
        run: docker run -p 2000:8080 -d --name shopee-food shopee-food-clone-ui
        
