name: ssh-into-aws-ec2

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: ap-southeast-1
  REMOTE_HOST: ec2-13-213-47-21.ap-southeast-1.compute.amazonaws.com
  REMOTE_USER: ec2-user
  PROJECT_NAME: shopee-food-clone-ui
  PROJECT_IMAGE: khanhlvm/shopee-food

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ env.REMOTE_HOST }}
          SSH_USER: ${{ env.REMOTE_USER }}
          SSH_KEY: ${{ secrets.SSH_EC2_KEY }} 
      - name: List home directory
        run: ssh ec2 'ls -la'
      - name: Check out the repo
        uses: actions/checkout@v3      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.PROJECT_IMAGE }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Pull image from docker hub to ec2
        run: ssh ec2 'docker pull ${{ env.PROJECT_IMAGE }}:master'
      - name: Remove container of project is running
        run: ssh ec2 'docker rm -f ${{ env.PROJECT_NAME }}'
      - name: Run image of project on ec2
        run: ssh ec2 'docker run -p 2000:8080 -d --name ${{ env.PROJECT_NAME }} ${{ env.PROJECT_IMAGE }}:master'
